<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinFormsERP.Core\WinFormsERP.Core.csproj" />
    <ProjectReference Include="..\WinFormsERP.Data\WinFormsERP.Data.csproj" />
  </ItemGroup>

</Project>
